services:
  - type: web
    name: artifact-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: KERAS_FILE_ID
        value: your-file-id-here
      - key: PKL_FILE_ID
        value: your-file-id-here
